/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 othermodel.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import {
  Environment,
  OrbitControls,
  FlyControls,
  Html,
  
} from "@react-three/drei";
import * as THREE from "three";

import { useState, useRef, Suspense, useEffect } from "react";
import ComputerScreenHTML from '../src/htmloverlay/computerscreen';

export default function Model({HTMLPosition, HTMLRotation,  handleDayNightToggle,
  daynighttogglestate}, props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/othermodel.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  const [screenPosition, setScreenPosition] = useState(
    new THREE.Vector3(
      -0.09495129436254501,
      0.930014729499817,
      4.181510925292969
    )
  );


  const monitorRef = useRef(null);
  const floorRef = useRef(null);
  const lightRef = useRef(null);



  console.log(nodes)
  useEffect(() => {
    if (actions) {
      actions[Object.keys(actions)[0]].play(); // Play the first animation
    }
  }, [actions]);

  useEffect(() => {
    if (lightRef.current) {
      console.log(lightRef);
      lightRef.current.lookAt(new THREE.Vector3(0, -10, 0));
    }
  }, [daynighttogglestate]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name='Day_Toggle'><mesh position={[3.9, 3.58, 3.87]} rotation-x={Math.PI / 2}>
          <cylinderGeometry args={[0.3, 0.3, 0.045]} />
          <meshBasicMaterial color="black" />
          <Html
            rotation-x={Math.PI / 2}
            transform
            occlude
            style={{ width: "17px", height: "19px" }}
            position={[0, 0.03, 0]}
          >
            <button onClick={handleDayNightToggle}>
              <div style={{ width: "100%", height: "100%" }}>
                
                {daynighttogglestate ? (
                <img
                  id="nightdaytoggle"
                  src={"/images/sun-regular-84.png"}
                  alt="Example image"
                />) : (<img
                  id="nightdaytoggle"
                  src={"/images/moon-regular-84.png"}
                  alt="Example image"
                />)
                }

              </div>
            </button>
          </Html>
        </mesh></group>
        <group name='Black_Boards'><mesh position={[-3.92, 2.2, 3.9]}>
          <boxGeometry args={[1.55, 2.075, 0.1]} />
          <meshBasicMaterial color="black" />

        </mesh>
        <mesh position={[3.92, 2.2, 3.9]} >
          <boxGeometry args={[1.55, 2.075, 0.1]} />
          <meshBasicMaterial color={new THREE.Color("rgb(0, 0, 0)")} />
        </mesh>
        </group>
        
        <group name="Fan_Base1" position={[-1.509, 1.361, 4.493]} rotation={[-Math.PI / 2, 0, 1.599]} scale={0.017}>
          <group name="Fan_Head2" position={[0, -0.525, 19.013]} rotation={[Math.PI / 2, -Math.PI / 4, 0]}>
            <group name="Fan_Blades7" position={[0, 1.746, 7.441]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
              <mesh name="Mesh_4" geometry={nodes.Mesh_4.geometry} material={materials['Material.003']} rotation={[0, 0, -Math.PI / 4]} />
            </group>
            <group name="Fan_Lock6" position={[-1.146, 3.729, -5.368]} rotation={[-Math.PI / 2, 0, 0]} scale={0.707}>
              <mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials['Material.003']} />
            </group>
            <group name="Fan_Tassle_024" position={[-4.833, -8.151, 10.498]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.698, 1]} />
            <group name="Fan_Tassle_015" position={[-8.352, 10.112, 10.542]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.666, 1]}>
              <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials['Material.003']} morphTargetDictionary={nodes.Mesh_2.morphTargetDictionary} morphTargetInfluences={nodes.Mesh_2.morphTargetInfluences} position={[0, -11.221, 0]} />
            </group>
            <group name="Fan_Tassle_033" position={[5.319, 7.091, 11.232]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.796, 1]} />
            <mesh name="Mesh_5" geometry={nodes.Mesh_5.geometry} material={materials['Material.003']} position={[0, 1.733, 7.621]} />
          </group>
          <mesh name="Mesh_6" geometry={nodes.Mesh_6.geometry} material={materials['Material.003']} />
        </group>
        <group name="Armature">
          <primitive object={nodes.Bone} />
        </group>
        <group name="Plane" position={[-0.014, 2.274, 3.616]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
        </group>
        <group name="Plane001" position={[-3.185, 4.01, 3.925]}>
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.001']} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials['Material.006']} />
        </group>
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[-3.941, 3.598, 4.144]} rotation={[Math.PI / 2, 0, 0]} scale={0.298} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.001']} position={[-3.96, 3.586, 3.892]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.023} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.001']} position={[-3.962, 3.585, 3.885]} rotation={[Math.PI / 2, -0.912, 0]} scale={0.015} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-4.095, 2.412, 3.072]} scale={0.822} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.002']} position={[-4.122, 1.193, 3.849]} rotation={[Math.PI / 2, 0, 0]} scale={0.028} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.001']} position={[-4.35, 2.73, 3.932]} rotation={[Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.001']} position={[-4.356, 2.407, 3.932]} rotation={[Math.PI / 2, -0.118, 0]} scale={0.049} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.001']} position={[-4.349, 2.063, 3.932]} rotation={[Math.PI / 2, -0.099, 0]} scale={0.049} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.001']} position={[-4.349, 1.712, 3.932]} rotation={[Math.PI / 2, -0.003, 0]} scale={0.049} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[3.801, 2.412, 3.072]} scale={0.822} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.002']} position={[3.775, 1.193, 3.849]} rotation={[Math.PI / 2, 0, 0]} scale={0.028} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['Material.001']} position={[3.674, 2.463, 3.932]} rotation={[Math.PI / 2, 0.021, 0]} scale={[0.056, 0.052, 0.052]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.001']} position={[4.228, 2.443, 3.932]} rotation={[Math.PI / 2, -0.131, 0]} scale={[0.055, 0.049, 0.053]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.001']} position={[4.087, 1.685, 3.932]} rotation={[Math.PI / 2, -0.09, 0]} scale={0.054} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.001']} position={[3.978, 2.079, 3.932]} rotation={[Math.PI / 2, -0.015, 0]} scale={0.055} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Material.001']} position={[3.974, 2.447, 3.932]} rotation={[Math.PI / 2, -0.144, 0]} scale={0.052} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.001']} position={[3.865, 1.685, 3.932]} rotation={[Math.PI / 2, -0.118, 0]} scale={[0.056, 0.05, 0.054]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.002']} position={[-2.796, 1.863, 2.755]} scale={[0.042, 0.023, 0.029]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-0.023, 3.802, 6.125]} scale={[0.029, 0.028, 0.266]} >
        {daynighttogglestate && (
          <rectAreaLight
            ref={lightRef}
            width={3} // Width of the rectangular l#fae978ight area
            height={0.5}
            position={[0, -10, 0]}
            color="#fae978"
            intensity={10}
          />
          
        )}
         {daynighttogglestate && (
      <mesh
        position={[-0.015, 2.71, 5.0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <boxGeometry args={[0.5, 4.6, 0.004]} />
        <meshBasicMaterial color={"#fae978"} />
      </mesh>
      )}
        </mesh>
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-3.563, 0.854, 5.062]} scale={[0.257, 0.295, 0.257]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[-2.592, 0.866, 3.52]} rotation={[0, -0.203, 0]} scale={[0.273, 0.307, 0.273]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.001']} position={[-1.452, 0.852, 4.494]} rotation={[0, 0.37, 0]} scale={[0.034, 0.033, 0.04]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['Material.008']} position={[-3.185, 0.539, 3.925]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.003']} position={[-0.6, 1.417, 4.804]} rotation={[0, 0.236, 0]} scale={[0.003, 0.047, 0.047]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.003']} position={[1.521, 0.698, 4.219]} rotation={[0, 0.248, 0]} scale={0.159} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.003']} position={[0.439, 1.012, 5.151]} rotation={[0, -1.037, 0]} scale={0.043} />
        <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials['Material.003']} position={[1.019, 1.719, 4.159]} rotation={[0, 0.236, 0]} />
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials['Material.003']} position={[-0.679, 1.644, 4.399]} rotation={[0, -0.358, 0]} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.003']} position={[-0.688, 1.585, 4.399]} rotation={[0, -0.358, 0]} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['Material.003']} position={[1.625, 1.8, 4.164]} rotation={[1.486, -0.325, -1.832]} scale={[1, 1.193, 1]} />
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['Material.003']} position={[1.706, 1.795, 4.168]} rotation={[1.491, -0.304, -1.831]} scale={[1, 0.918, 1]} />
        <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials['Material.003']} position={[1.601, 1.322, 4.213]} rotation={[-Math.PI, 1.06, -Math.PI]} scale={[0.889, 1.072, 0.889]} />
        <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials['Material.003']} position={[1.583, 1.074, 4.186]} rotation={[0, 0.248, 0]} />
        <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials['Material.003']} position={[1.594, 0.718, 4.221]} rotation={[1.543, -0.111, -1.82]} scale={[0.839, 1.001, 0.839]} />
        <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials['Material.003']} position={[1.666, 0.718, 4.25]} rotation={[1.548, -0.091, -1.82]} scale={[0.839, 0.77, 0.839]} />
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials['Material.003']} position={[1.715, 0.694, 4.191]} rotation={[1.553, -0.071, -1.819]} scale={[0.707, 0.959, 0.708]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[3.502, 0.852, 4.595]} rotation={[0, -0.002, 0]} scale={[0.034, 0.033, 0.04]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.003']} position={[3.215, 1.381, 4.716]} rotation={[0, -0.006, 0]} scale={[0.035, 0.026, 0.035]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[2.373, 0.716, 4.083]} scale={0.177} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.003']} position={[-0.095, 1.93, 4.182]} rotation={[-0.303, 0.482, 0.144]}> <ComputerScreenHTML
            HTMLRotation={HTMLRotation}
            HTMLPosition={HTMLPosition}
          /></mesh>
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.002']} position={[-7.298, 1.863, 2.755]} scale={[0.042, 0.023, 0.029]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.002']} position={[5.027, 1.863, 2.755]} scale={[0.042, 0.023, 0.029]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.001']} position={[-7, 4.162, 3.249]} scale={[0.642, 0.117, 0.642]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['Material.001']} position={[-7, 0.339, 3.249]} scale={[0.642, 0.117, 0.642]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['Material.001']} position={[7.709, 4.162, 8.212]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.642, 0.117, 0.642]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['Material.001']} position={[-7.76, 4.162, 8.212]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.642, 0.117, 0.642]} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['Material.009']} position={[0.39, 0.762, 2.751]} scale={0.022} />
        <group name="Plane028" position={[3.134, 0.539, 13.784]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh name="Plane055" geometry={nodes.Plane055.geometry} material={materials['Material.008']} />
          <mesh name="Plane055_1" geometry={nodes.Plane055_1.geometry} material={materials['Material.006']} />
        </group>
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['Material.003']} morphTargetDictionary={nodes.Plane015.morphTargetDictionary} morphTargetInfluences={nodes.Plane015.morphTargetInfluences} position={[1.515, 2.254, 3.903]} rotation={[Math.PI / 2, 0.02, 1.19]} scale={[0.029, 0.12, 0.031]} />
      </group>
    </group>
  )
}

useGLTF.preload('/othermodel.glb')
