/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 rvised.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/rvised.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.134, 4.013, 0.93]} rotation={[-Math.PI / 2, 0, 0]} scale={9.496}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0.171, 0]}>
            <mesh geometry={nodes.pCube94_corpo_do_teclado_0.geometry} material={materials['Material.040']} position={[0, -36.238, 0]} />
            <mesh geometry={nodes.pCube94_teclado_0.geometry} material={materials['Material.002']} position={[0, -36.238, 0]} />
          </group>
          <group position={[11.764, 0.189, -0.483]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.pCylinder2_mouse_0.geometry} material={materials['Material.040']} position={[0, -36.238, 0]} />
            <mesh geometry={nodes.pCylinder2_scroll_0.geometry} material={materials.scroll} position={[0, -36.238, 0]} />
          </group>
          <group position={[-0.023, -31.065, -3.689]} rotation={[-Math.PI, 0, -Math.PI]} scale={[9.223, 4.632, 0.268]}>
            <mesh geometry={nodes.tvpCube1_tvcorpo2_tv_0.geometry} material={materials['Material.040']} scale={1.379} />
            <mesh geometry={nodes.tvpCube1_tvcorpo_da_tv_0.geometry} material={materials['Material.040']} scale={1.379} />
            <mesh geometry={nodes.tvpCube1_tvpes_da_tv1_0.geometry} material={materials['Material.040']} scale={1.379} />
            <mesh geometry={nodes.tvpCube1_tvtela_da_tv_0.geometry} material={materials.tvtela_da_tv} scale={1.379} />
          </group>
        </group>
      </group>
      <group position={[-3.053, 0.522, 3.848]} rotation={[-Math.PI / 2, 0, 0]} scale={0.009}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-93.113, -7.437, 83.598]} rotation={[-Math.PI / 2, 0, 1.543]} scale={125.659}>
            <group position={[-0.138, -0.611, -0.031]} rotation={[0, 1.294, 0]} scale={[0.701, 0.695, 0.836]}>
              <mesh geometry={nodes.Plane_fabric_0.geometry} material={materials['Material.017']} position={[0.94, -3.326, 2.611]} rotation={[-1.475, -0.286, 0.335]}>
                <mesh geometry={nodes.Cube004_fabric_0.geometry} material={materials['Material.017']} position={[0.611, 0, 0.183]} rotation={[0, -1.289, 0]} scale={[0.845, 1, 0.982]} />
                <mesh geometry={nodes.Cube005_fabric_0.geometry} material={materials['Material.017']} position={[0.517, -0.002, 0.286]} rotation={[0, -1.289, 0]} scale={[0.845, 1, 0.982]} />
                <mesh geometry={nodes.Cube_fabric_0.geometry} material={materials['Material.004']} position={[0.732, 0.09, 0.152]} rotation={[0, -1.289, 0]} scale={[0.845, 1, 0.982]} />
                <mesh geometry={nodes.Cylinder_Wood_0.geometry} material={materials['Material.023']} position={[0.733, 0, 0.154]} rotation={[0, -1.289, 0]} scale={[0.845, 1, 0.982]} />
              </mesh>
            </group>
          </group>
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-3.697, -0.515, 1.32]} rotation={[0, 0, -1.423]} scale={0.055}>
          <mesh geometry={nodes.Cube001_0.geometry} material={materials['Material.031']} position={[2.198, 14.784, -9.766]} />
          <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.018']} position={[1.933, 13.001, -10.747]} scale={0.636}>
            {/* <mesh geometry={nodes.Cube001_1_1.geometry} material={materials['Material.029']} /> */}
            <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.014']} />
          </mesh>
        </group>
        <group position={[-4.355, -3.5, 0.738]} rotation={[0, 0, 1.751]} scale={[0.131, 0.183, 0.067]}>
          <mesh geometry={nodes.Cube002_0.geometry} material={materials['Material.035']} position={[-0.971, -13.728, -8.932]} scale={0.752} />
        </group>
        <group position={[-1.313, -0.417, 0.12]} rotation={[0, 0, -0.018]} scale={0.342}>
          <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.039']} position={[1.91, -0.597, -0.137]}>
            <mesh geometry={nodes.Cube003_0.geometry} material={materials['Material.031']} />
            {/* <mesh geometry={nodes.Cube003_1_1.geometry} material={materials['Material.030']} /> */}
          </mesh>
        </group>
        <group position={[-4.135, -0.484, 1.088]} rotation={[0, 0, 0.059]} scale={0.163}>
          <mesh geometry={nodes.Cube005_0.geometry} material={materials['Material.025']} position={[5.907, -0.587, -3.149]} scale={0.725}>
            <mesh geometry={nodes.Cube010_0.geometry} material={materials['Material.025']} position={[-0.09, 0.005, 0.695]} />
          </mesh>
        </group>
        <group position={[3.452, -3.853, 1.647]} rotation={[0, 0, -1.551]} scale={0.805}>
          <mesh geometry={nodes.Cube006_0.geometry} material={materials['Material.031']} position={[-0.631, -4.385, 0.537]} />
          <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.030']} position={[-0.631, -4.385, 0.537]} />
          <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.001']} position={[-0.631, -4.385, 0.537]} />
          <mesh geometry={nodes.Cube006_3.geometry} material={materials['Material.008']} position={[-0.631, -4.385, 0.537]} />
        </group>
        <group position={[-3.853, -0.896, 1.087]} rotation={[0, 0, 2.166]} scale={[0.131, 0.183, 0.067]}>
          <mesh geometry={nodes.Cube009_0.geometry} material={materials['Material.035']} position={[-3.248, -3.276, -7.607]} scale={0.725} />
        </group>
        <group position={[-4.138, -0.481, 1.287]} rotation={[0, 0, -3]} scale={[0.131, 0.183, 0.067]}>
          <mesh geometry={nodes.Cube012_0.geometry} material={materials['Material.035']} position={[-7.22, 0.923, -8.415]} scale={-0.637} />
        </group>
        <group position={[-1.443, -0.487, 1.57]} rotation={[0, 0, -0.826]} scale={0.765}>
          <mesh geometry={nodes.Cube015_0.geometry} material={materials['Material.034']} position={[0.774, 0.649, -0.184]}>
            <mesh geometry={nodes.Cube015_1.geometry} material={materials['Material.032']} />
            <mesh geometry={nodes.Cube015_3.geometry} material={materials['Material.021']} position={[0, -0.032, 0]} />
          </mesh>
          <mesh geometry={nodes.Cube015_2.geometry} material={materials['Material.031']} position={[0.774, 0.617, -0.184]} />
          <mesh geometry={nodes.Cube015_4.geometry} material={materials['Material.022']} position={[0.774, 0.649, -0.184]} />
        </group>
        <group position={[-2.88, -0.702, 0.565]} scale={0.306}>
          <mesh geometry={nodes.Cube016_0.geometry} material={materials['Material.023']} position={[1.561, -0.384, -0.468]}>
            <mesh geometry={nodes.Cube016_1.geometry} material={materials['Material.034']} />
            <mesh geometry={nodes.Cube016_2.geometry} material={materials['Material.039']} />
            <mesh geometry={nodes.Cube016_3.geometry} material={materials['Material.030']} />
          </mesh>
        </group>
        <group position={[-3.835, -0.532, 1.32]} rotation={[0, 0, -1.604]} scale={0.055}>
          <mesh geometry={nodes.Cube017_0.geometry} material={materials['Material.031']} position={[-0.15, 4.535, 0]}>
            <mesh geometry={nodes.Cube017_2.geometry} material={materials['Material.014']} position={[0.115, 12.914, -9.682]} scale={0.645} />
            <mesh geometry={nodes.Cube017_3.geometry} material={materials['Material.018']} position={[0.033, 12.971, -10.251]} scale={0.725} />
          </mesh>
        </group>
        <group position={[-7.169, -0.043, -0.621]} scale={0.422}>
          <mesh geometry={nodes.Cube020_1.geometry} material={materials['Material.024']} position={[12.239, -6.918, 1.63]} scale={[0.249, 0.666, 0.322]} />
        </group>
        <group position={[-2.139, -1.498, 0.048]} rotation={[0, 0, -1.175]} scale={0.31}>
          <mesh geometry={nodes.Cube021_0.geometry} material={materials['Material.034']} />
          <mesh geometry={nodes.Cube021_1.geometry} material={materials['Material.032']} />
          <mesh geometry={nodes.Cube021_2.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Cube021_3.geometry} material={materials['Material.030']} />
          <mesh geometry={nodes.Cube021_4.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cube021_5.geometry} material={materials['Material.018']} />
        </group>
        <group position={[-0.346, -3.712, 0.162]} rotation={[0, 0, -1.559]} scale={0.232}>
          <mesh geometry={nodes.Cube023_3.geometry} material={materials['Material.030']} position={[-0.01, -0.826, 0]}>
            <mesh geometry={nodes.Cube023_6.geometry} material={materials['Material.016']}>
              <mesh geometry={nodes.Cube023_0.geometry} material={materials['Material.034']}>
                <mesh geometry={nodes.Cube023_1.geometry} material={materials['Material.032']} />
                <mesh geometry={nodes.Cube023_2.geometry} material={materials['Material.031']} />
                <mesh geometry={nodes.Cube023_4.geometry} material={materials['Material.014']} />
                <mesh geometry={nodes.Cube023_5.geometry} material={materials['Material.015']} position={[0, 0, 0.012]} />
              </mesh>
            </mesh>
          </mesh>
        </group>
        <group position={[-2.336, -0.411, 2.485]} rotation={[Math.PI / 2, 0.03, 0]} scale={0.66}>
          <mesh geometry={nodes.Cylinder_0.geometry} material={materials['Material.031']} rotation={[0.024, -0.044, 0.012]} />
          {/* <mesh geometry={nodes.Cylinder_1_1.geometry} material={materials['Material.029']} /> */}
          <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.037']} />
        </group>
        <group position={[-3.603, -0.862, 0.088]} rotation={[0, 0, -0.637]} scale={0.225}>
          <mesh geometry={nodes.Cylinder003_0.geometry} material={materials['Material.019']}>
            <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.020']} scale={[1, 1, 1.228]} />
          </mesh>
          <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-0.477, -0.852, 1.499]} rotation={[0.044, 0.031, 2.732]} scale={0.08}>
          <mesh geometry={nodes.Cylinder006_0.geometry} material={materials['Material.027']} />
          <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Material.026']} />
        </group>
        <group position={[0.046, -2.638, 1.154]} rotation={[-0.054, 0, -1.024]} scale={0.08}>
          <mesh geometry={nodes.Cylinder007_0.geometry} material={materials['Material.027']} position={[-9.726, -25.698, -12.416]} scale={0.752} />
        </group>
      </group>
      <mesh geometry={nodes.Cylinder012.geometry} material={materials['Material.040']} position={[-2.149, -0.188, 2.947]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -0.006, -1]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.023']} position={[-1.976, 0.117, 2.956]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.574, -0.019, -0.574]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials['Material.007']} position={[-1.81, 1.426, 0.103]} rotation={[0, Math.PI / 2, 0]} scale={[0.144, 1.676, 1.98]} />
      <group position={[0.049, 1.433, 2.109]} scale={[0.144, 1.676, 1.873]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube002_4.geometry} material={materials['Material.035']} />
      </group>
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.004']} position={[-1.822, -0.302, 1.969]} scale={[2.021, 0.099, 2.018]} />
    </group>
  )
}

useGLTF.preload('/rvised.glb')
