/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 rvised.glb --shadows --exportdefault 
*/

import React from "react";
import { Html } from "@react-three/drei";

import { useGLTF } from "@react-three/drei";
import Corkboard from "./Corkboard";
import { useRef, useEffect, useState } from "react";
import { useFrame } from "@react-three/fiber";
import VaporEffect from "./VaporEffect";
import * as THREE from "three";


import ScrollTrigger from "gsap/ScrollTrigger";
import { Text3D, PivotControls } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { gsap } from "gsap";
import { useGSAP } from "@gsap/react";
import { TextPlugin } from "gsap/TextPlugin";
import Component from "./ContactForm";
import Glasses from "@/Glasses";
import Lamp from "./Lamp";



export default function PCModel({htmlPresent,handleHTMLPresent,arrowPresent, handleArrowPresent, animationLocation
  
}) {
  const { nodes: nodes, materials: materials } = useGLTF(
    "compressedOffice.glb",
    true
  );
  const { nodes: nodes2, materials: materials2 } = useGLTF(
    "OfficeProps.glb",
    true
  );

  
  const modelRef = useRef();

  const { camera, viewport, size  } = useThree();

  gsap.registerPlugin(useGSAP);
  gsap.registerPlugin(TextPlugin);
  gsap.registerPlugin(ScrollTrigger);

  const [animationEnded, setAnimationEnded] = useState(true);
  const [deskchairtransparent, setdeskchairtransparent] = useState(false);
  const [scrollProgtoMonitorComplete, setScrollProgtoMonitorComplete]=useState(false);
  




  useGSAP(
    () => {
     



    },
    { dependencies: [deskchairtransparent], revertOnUpdate: true }
  );

  useGSAP(() => {
    const intro = gsap.timeline({ repeat: 0 });




    


    intro.from(modelRef.current.scale, {
      x: 0.01,
      y: 0.01,
      z: 0.01,
      duration: 1.5,
      delay: 0.5,
      ease: "elastic.out",
    });

    intro.to(
      modelRef.current.rotation,
      {
        x: 0,
        y: 0,
        z: 0,
        duration: 2,
        delay: 0.5,
        ease: "elastic.out",
      },
      0
    );
  
  //  intro.to(".overlay-text-container", {
  //     y: 0,

  //     duration: 1,
  //     ease: "power1.in",
  //     opacity: 1,
      
  //   },1);
  //   intro.to(".title-text", {
  //     y: 0,

  //     duration: 1,
  //     ease: "power1.in",
  //     opacity: 1,
      
  //   },1);
  //   intro.to(".navbar", {
  //     x: 0,

  //     duration: 1,
  //     ease: "power1.in",
  //     opacity: 1,
      
  //   },1);
     

  
  
  
  
  
  
  },[])



  useGSAP(() => {

    const homeCamera = gsap.timeline({
      paused: true,
      repeat: 0,
     
    });

    homeCamera.to(
      camera.rotation,
      { 
        x: -0.4,
        y: 0.003,
        z: 0,
        duration: 0.5,
        delay: 0,
      },
      0
    );
    
    if (size.width >= 1920) {
      homeCamera.to(
        camera.position,
        {
          x: 0,
          y: 2.4,
          z: 5.55,
          duration: 0.5,
          delay: 0,
          ease: "power1.in",
          
        },
        0
      );
    }
    else {
      homeCamera.to(
        camera.position,
        {
          x: 0,
          y: 2.25,
          z: 5.55,
          duration: 0.5,
          delay: 0,
          ease: "power1.in",
          
        },
        0
      );
    }



   
    const monitorCamera = gsap.timeline({
      paused: true,
      repeat: 0,
     
      
       
        
      
    });

    monitorCamera.to(
      camera.rotation,
      {
        x: -0.055,
        y: 0.795,
        z: 0.0375,
        duration: .75,
        delay: 0,
        ease: "power1.out",
        
      },
      0
    );
    monitorCamera.to(
      camera.position,
      {
        x: 0.6, 
        y: -0.1, 
        z: 0.23, 
        duration: .75,
        delay: 0,
        ease: "power1.out",
      },
      0
    );
   

    const projectsCamera = gsap.timeline({
      paused: true,
      repeat: 0,
     
    });

    projectsCamera.to(
      camera.rotation,
      {
        x: 0,
        y: -0.77,
        z: 0,
        duration: .75,
        delay: 0,
        ease: "power1.out",
      },
      0
    );
    projectsCamera.to(
      camera.position,
      {
        x: -1,
        y: 0.075,
        z: .6,
        duration: .75,
        delay: 0,
        ease: "power1.out",
        
      },
      0
    );

    const contactCamera = gsap.timeline({
      paused: true,
      repeat: 0,
      
    });

    contactCamera.to(
      camera.rotation,
      {
        x: -1.4,
        y: 0,
        z: -.55,
        duration: .75,
        delay: 0,
         ease: "power1.out",
      },
      0
    );
    contactCamera.to(
      camera.position,
      {
        x: 0.115,
        y: 0.6,
        z: -0.14,
        duration: .75,
        delay: 0,
        ease: "power1.out",
      },
      0
    );
   

    if (animationLocation === 'About') {
      monitorCamera.play() 




      setdeskchairtransparent(true);
      setScrollProgtoMonitorComplete(false)
        
      setAnimationEnded(false);
      modelRef.current.rotation.set(0, 0, 0);

      handleHTMLPresent();
      handleArrowPresent();
      


      const aboutMe = gsap.timeline({ repeat: 0 });

      aboutMe.fromTo(
        ".about-me-header",
    
        {
         
          y: -5,
          ease: "back.inOut",
    
          duration: .5,
    
          opacity: 0,
          delay: 0,
        },
        {
          y: 0,
          ease: "back.inOut",
    
          duration: 1.0,
    
          opacity: 1,
          delay: 0,
        },1
      );

      aboutMe.fromTo(
        ".chandler-link-bar",
    
        {
         
          y: 5,
          ease: "back.inOut",
    
          duration: 1,
    
          opacity: 0,
          delay: 0,
        },
        {
          y: 0,
          ease: "back.inOut",
    
          duration: 1.0,
    
          opacity: 1,
          delay: 0,
        },1
      );
    
      aboutMe.from(".about-me-section", {
        y: 10,
       
    
        duration: 1,
    
        opacity: 0,
        delay: 0,
      },1);
      aboutMe.from(".chandler-pic", {
        x: -10,
       
    
        duration: 1,
    
        opacity: 0,
        delay: 0,
      } ,1);





    }
    if (animationLocation === 'Projects') {
      // setdeskchairtransparent(true);
      projectsCamera.play()
      handleHTMLPresent();
      handleArrowPresent();
      modelRef.current.rotation.set(0, 0, 0);
      
    }
    if (animationLocation === 'Contact') {
     contactCamera.play()
     handleHTMLPresent();
     handleArrowPresent();
     setTimeout(() => {
      setScrollProgtoMonitorComplete(true)
     }, 500);
     modelRef.current.rotation.set(0, 0, 0);
     
    }
    if (animationLocation=='Home') {
homeCamera.play();

handleArrowPresent();
setTimeout(() => {
  handleHTMLPresent();
  setdeskchairtransparent(false)
  setScrollProgtoMonitorComplete(false)
}, 400);
setScrollProgtoMonitorComplete(false)

    }

  }, [animationLocation]);










  function GlowingText() {
    const glowingTextRef = useRef();

    return (
      <>
        <Text3D
          ref={glowingTextRef}
          font={"fonts/3dfont3.json"}
          size={0.05}
          scale={[0.4, 0.3, .25]}
          rotation={[Math.PI / 2, 0, 0]}
          height={0.011}
          width={0.1}
          curveSegments={10}
          position={[-0.095, 0.06, 0.1625]}
        >
          {`Chandler Casey\nFull-Stack Developer`}
          <pointLight position={[-0.05, 0.025, 0]} decay={8}  intensity={.015} color="#98fac1" />
          <meshStandardMaterial
            attach="material"
            color="#98fac1"
            emissive="#98fac1"
            emissiveIntensity={.2}
          />
        </Text3D>
      </>
    );
  }

  return (
    <>
    <group ref={modelRef}  position={[0,0,-1]}>
      <group
        
        dispose={null}
        position={[-0.045, -0.35, -0]}
        rotation-y={[0.79]}
        // rotation-x={[.1]}
        
        rotation-x={[0]}
        scale={[0.19, 0.24, 0.19]}
        onPointerDown={(e) => { if(animationLocation==="Home" ||animationLocation === "") {const intro = gsap.timeline({ repeat: 0 });
        



    


        intro.to(modelRef.current.scale, {
          x: 0.98,
          y: 0.98,
          z: 0.98,
          duration: 1,
          delay: 0,
          ease: "elastic.out",
        },
        );
       
        intro.to(modelRef.current.scale, {
          x: 1,
          y: 1,
          z: 1,
          duration: 1,
          delay: 0,
          ease: "elastic.out",
        },
        0.2);
    
        intro.to(
          modelRef.current.rotation,
          {
            x: 0,
            y: 0,
            z: 0,
            duration: 2,
            delay: 0.5,
            ease: "elastic.out",
          },
          0
        );
      
        
      
      
      }
    }
  }
      >
        <mesh
          position={[0, -0.65, 0]}
          rotation-x={[-Math.PI / 2]}
          scale={[400, 400, 1]}
          receiveShadow
        >
          <planeGeometry args={[10, 10]} />
          <shadowMaterial opacity={.1} />
        </mesh>

        <group
          position={[-2.237, 0.576, 0.969]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={12.089}
          
        >
          <GlowingText />

<group position={[0,0,.01]} scale={[.95,1,1]} >
          <mesh
            material={materials["Material.023"]}
            scale={[0.5, 0.2, 0.2]}
            position={[-0.0, 0.05, 0.0725]}
          >
            <boxGeometry args={[0.3, 0.15, 0.01]} />
           
          </mesh>

<group position={[-.01,0,0]} scale={[.9,1,1]}>
          <mesh rotation={[-Math.PI / 1.65,-Math.PI / 1,0]} scale={[0.1, 0.15, 0.2]}  position={[-0.05, 0.05, 0.0845]}>
            <boxGeometry args={[0.3, 0.15, 0.01]}/>
            <meshStandardMaterial  color={"#ffffff"}
            metalness={0.65}
            roughness={1}/>
             
            <Html position={[-.001,-.003,0]} scale={[.1,.05,.05]} transform> 
            <div
                    className="shelflogo"
                    style={{
                      width: "80px",
                      height: "80px",

                      position: "relative",
                      zIndex: 1,
                      transform: "rotate(180deg)",
                    }}
                  >
                    <img
                      src="images/typescript.png"
                      style={{
                        width: "100%",
                        height: "100%",

                        position: "absolute",
                        zIndex: 1,
                      }}
                    />
                  </div>

            </Html>
            </mesh>
        
          <mesh rotation={[-Math.PI / 1.65,-Math.PI / 1,0]} scale={[0.1, 0.15, 0.2]}  position={[-0.01, 0.05, 0.0845]}>
            <boxGeometry args={[0.3, 0.15, 0.01]}/>
            <meshStandardMaterial  color={"#ffffff"}
            metalness={0.65}
            roughness={1}/>
              <Html position={[-.001,-.003,0]} scale={[.1,.05,.05]} transform> 
            <div
                    className="shelflogo"
                    style={{
                      width: "80px",
                      height: "80px",

                      position: "relative",
                      zIndex: 1,
                      transform: "rotate(180deg)",
                    }}
                  >
                    <img
                      src="images/react.svg"
                      style={{
                        width: "100%",
                        height: "100%",

                        position: "absolute",
                        zIndex: 1,
                      }}
                    />
                  </div>

            </Html>
          </mesh>
          <mesh rotation={[-Math.PI / 1.65,-Math.PI / 1,0]} scale={[0.1, 0.15, 0.2]}  position={[0.03, 0.05, 0.0845]}>
            <boxGeometry args={[0.3, 0.15, 0.01]}/>
            <meshStandardMaterial  color={"#ffffff"}
            metalness={0.65}
            roughness={1}/>
              <Html position={[-.001,-.003,0]} scale={[.1,.05,.05]} transform> 
            <div
                    className="shelflogo"
                    style={{
                      width: "80px",
                      height: "80px",

                      position: "relative",
                      zIndex: 1,
                      transform: "rotate(180deg)",
                    }}
                  >
                    <img
                      src="images/nodejs.png"
                      style={{
                        width: "100%",
                        height: "100%",

                        position: "absolute",
                        zIndex: 1,
                      }}
                    />
                  </div>

            </Html>
          </mesh>
          <mesh rotation={[-Math.PI / 1.65,-Math.PI / 1,0]} scale={[0.1, 0.15, 0.2]}  position={[0.07, 0.05, 0.0845]}>
            <boxGeometry args={[0.3, 0.15, 0.01]}/>
            <meshStandardMaterial  color={"#ffffff"}
            metalness={0.65}
            roughness={1}/>
              <Html position={[-.001,-.003,0]} scale={[.1,.05,.05]} transform> 
            <div
                    className="shelflogo"
                    style={{
                      width: "80px",
                      height: "80px",

                      position: "relative",
                      zIndex: 1,
                      transform: "rotate(180deg)",
                    }}
                  >
                    <img
                      src="images/postgres.svg"
                      style={{
                        width: "100%",
                        height: "100%",

                        position: "absolute",
                        zIndex: 1,
                      }}
                    />
                  </div>

            </Html>
          </mesh>
          </group>
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group position={[0, 0.171, 0]}>
              <mesh
                emissive="black"
                castShadow
                receiveShadow
                geometry={nodes.pCube94_corpo_do_teclado_0.geometry}
                material={materials["Material.035"]}
              />
              <mesh
                emissive="black"
                castShadow
                receiveShadow
                geometry={nodes.pCube94_teclado_0.geometry}
                material={materials["Material.003"]}
              />
            </group>
            <group
              position={[11.764, 0.189, -0.483]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                emissive="black"
                castShadow
                receiveShadow
                geometry={nodes.pCylinder2_mouse_0.geometry}
                material={materials["Material.035"]}
                position={[0.767, 0, 0]}
              />
              <mesh
                emissive="black"
                castShadow
                receiveShadow
                geometry={nodes.pCylinder2_scroll_0001.geometry}
                material={materials["scroll.001"]}
                position={[0.8, 0, 0]}
              />
            </group>
            <group
              position={[-0.023, 3.798, -3.962]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[9.223, 4.632, 0.268]}
            >
              <mesh
                emissive="black"
                castShadow
                receiveShadow
                geometry={nodes.tvpCube1_tvcorpo2_tv_0.geometry}
                material={materials["Material.035"]}
              />
             
              <mesh
                emissive="black"
                castShadow
                receiveShadow
                geometry={nodes.tvpCube1_tvpes_da_tv1_0.geometry}
                material={materials["Material.035"]}
                
              />
               <mesh
                emissive="black"
                castShadow
                receiveShadow
                geometry={nodes.tvpCube1_tvcorpo_da_tv_0.geometry}
                material={materials["Material.035"]}
                position={[0,.025,0]}
                scale={1.15}
              />
              <mesh
                emissive="black"
                castShadow
                receiveShadow
                geometry={nodes.tvpCube1_tvtela_da_tv_0.geometry}
                material={materials["tvtela_da_tv.002"]}
                position={[0,.025,0]}
                scale={1.15}
              >
                <Html
                  className="computer-monitor"
                  position={
                    deskchairtransparent
                      ? [0.364, -100, -0.7]
                      : [0.364, -0.0, -0.7]
                  }
                  scale={[0.08, 0.58, 0.01]}
                  rotation={[Math.PI, 0, 0]}
                  transform
                  occlude
                  pointerEvents="none"
                >
                  <div
                    className="monitor-screen"
                    style={{
                      width: "68px",
                      height: "120px",

                      position: "relative",
                      zIndex: 1,
                      transform: "rotate(90deg)",
                    }}
                  >
                    <img
                      src="images/lava.gif"
                      style={{
                        width: "400%",
                        height: "400%",

                        position: "absolute",
                        zIndex: 1,
                      }}
                    />
                  </div>
                </Html>

                <Html
                  position={deskchairtransparent ? [0, 0, -0.7] : [0, 100, 0]}
                  rotation-y={[Math.PI]}
                  scale={0.045}
                  transform
                >
                  <div
                    style={{
                      width: "120px",
                      height: "120px",
                      position: "relative",
                      zIndex: 1,
                    }}
                  >
                    <div className="computer-html">
                      <div className="html-container">
                        <div className="html-container-wrapper">
                          <div className="chandler-pic-column">
                            <img
                              className="chandler-pic"
                              src="images/chandler-pic.jpg"
                            />
                            <div className="chandler-link-bar">
                            <div className="chandler-links-container">
                            <a className="chandler-links" href="images/Resume.pdf" target="_blank"><img className="boxicon-pdf" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAeRJREFUaEPtmY1tAjEMhe1J2tuknaR0ksIk0ElKJymbuPciG0VVuETklyonIQHJJf5sJ/G9Y3rwix/cfpoAvSOYFAEReSaiDyJ6ISJ8z7n2zHzIGcC/Nwqgxv+UmlDHKQaRAnAkol1hAAxXBCIFQCoYb0NmQ7QE2MPrAWdkQTQDWBcuiwg2gqIQTQHg/dIQzQFKQ3QBKAnRDaAURFeAEhDdAXIhhgDYgsD2u3WQDgNwC2IYgHvLkQmwnpw1i7loYGYEZgSiSbLdYabQTKGZQvVKiQXOZeaLSi9vnnrxiv+1PICOhA/UDdOUFmu3AN1K1WqLWJ9xTfD6ZuaTPi7umHnxxLBPZj4rDPQl3OPgiQjQV4UilG21AaDUfa2ev6jR+H30vqMNl1MeRAT6EiJhAFHBrAUADDoEImBwAPABAeVSSIHQ/gTI5hHwJ/S8+9dY181LOXjdAGxNuMg1BxARf2IzJgRwYuZ3T1IZKoUsz82BPgCErLPmPwAt58cHCKQXYK7bqLb3W8QJByzOgdx3CW7tbM3V7Jk4ATjYZQL8h2rUjv97syDnPrej5a6BWq+YUsDc+ZELgJ0Ee332jpJisdcn6n13wqcMqpWllcMtQE5aX7mSPCsCsQF6tydFoLeRMwIjR+AXuEldQDRZKqkAAAAASUVORK5CYII="/> Resume</a>
                            </div>
                            <div className="chandler-links-container">
                            <a className="chandler-links" href="https://www.linkedin.com/in/chandler-casey1/" target="_blank"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAa1JREFUaEPtme1xwjAMhqVNyiQtkxQmKUxSNimdBDZR8/acXuqz4oTKlXMn/+HggqJHb/ThmGnjizfuPwWAt4KhQLcKiMgLEb0T0ZOzk3ciOjLzteSH+giJyAcRAaKHdWfm3VoA6cHz0QdmLgZ7ToEAsFTQUoHTYOwsIkju18HJk6Wjmi0rAFSDy/QmInJI1aophwlAyUhS4tbUeyKyAFBLmYg0T3gLAAR5248QEaErXpDEoEndGg2v+bJSYHQUIP86YlgDNI94fgMrAJRQRH+6MC9NZ6ZSXxh/w3/x+OFztIP/Pg/fUY7VZQVQTWKl1KLMnvMekvWTt7mm6A1wmHN+BBnKsQrhCrA0YeaaYjcAcJKZ8zz6YdT2Ie4A2cz0q58syQVXAKXhFUcTbTj0BtCSc5/vdXsFwMuBUp3fPEC1r1jvias3VBqZpkDVXgBkTagasVBA2WN7l9HIgVAgJTM2NJ9ZYuebkWNh+sQLsNKL4iX2vs1ZKbB0Mja/LgDMQ7rS4CMK9HTAcWXmfYl57nwASYcx2PuU5rEjppUKu10ex6xuoU83DgVCgT9G4AsukZtAqVJVsQAAAABJRU5ErkJggg=="/> LinkedIn</a>
                            </div>
                            </div>
                          </div>
                          <div className="about-me-column">
                            <h1 className="about-me-header">
                               I'm Chandler, a Full-Stack Developer.
                            </h1>
                            <div className="about-me-section">
                              
                              <p className="pb-1">
                                I’m a creative, solutions-driven full-stack
                                software engineer focused on intuitive design
                                and functionality. Proficient in the MERN stack,
                                TypeScript, PostgreSQL, Next.js, Python, and
                                Three.js, I build efficient applications that
                                emphasize user experience.
                              </p>
                              <p className="pb-1">
                                Outside of coding, I enjoy baking, playing the
                                trumpet, and building PCs.
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </Html>
              </mesh>
            </group>
          </group>
        </group>
        <group
          position={[-3.053, 0.522, 4]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.01,.01,.009]}
        >
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              position={[-93.113, -7.437, 83.598]}
              rotation={[-Math.PI / 2, 0, 1.543]}
              scale={125.659}
            >

              ///couch
              <group
                position={[-0.138, -0.611, -0.031]}
                rotation={[0, 1.294, 0]}
                scale={[0.701, 0.695, 0.836]}
              >
                <mesh
                  castShadow
                  
                  geometry={nodes.Plane_fabric_0.geometry}
                  material={materials["Material.017"]}
                  position={[0.94, -3.326, 2.611]}
                  rotation={[-1.475, -0.286, 0.335]}
                >
                  <mesh
                    castShadow
                    
                    geometry={nodes.Cube004_fabric_0.geometry}
                    material={materials["Material.017"]}
                    position={[0.611, 0, 0.183]}
                    rotation={[0, -1.289, 0]}
                    scale={[0.845, 1, 0.982]}
                  />
                  <mesh
                    castShadow
                    
                    geometry={nodes.Cube005_fabric_0.geometry}
                    material={materials["Material.017"]}
                    position={[0.517, -0.002, 0.286]}
                    rotation={[0, -1.289, 0]}
                    scale={[0.845, 1, 0.982]}
                  />
                  <mesh
                    castShadow
                   
                    geometry={nodes.Cube_fabric_0.geometry}
                    material={materials["Material.004"]}
                    position={[0.732, 0.09, 0.152]}
                    rotation={[0, -1.289, 0]}
                    scale={[0.845, 1, 0.982]}
                  />
                  <mesh
                    castShadow
                    
                    geometry={nodes.Cylinder_Wood_0.geometry}
                    material={materials["Material.023"]}
                    position={[0.733, 0, 0.154]}
                    rotation={[0, -1.289, 0]}
                    scale={[0.845, 1, 0.982]}
                  />
                </mesh>
              </group>
            </group>
          </group>
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group
            position={[-3.697, -0.515, 1.32]}
            rotation={[0, 0, -1.423]}
            scale={0.055}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_3.geometry}
              material={materials["Material.018"]}
              position={[1.933, 13.001, -10.747]}
              scale={0.636}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_1.geometry}
                material={materials["Material.029"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_2.geometry}
                material={materials["Material.014"]}
              />
            </mesh>
          </group>

          <group
            position={[-4.355, -3.6, 0.738]}
            rotation={[0, 0, 1.751]}
            scale={[0.131, 0.183, 0.067]}
          >
            <mesh
              geometry={nodes.Cube002_0.geometry}
              material={materials["Material.035"]}
              position={[-0.0, -13.5, -8.932]}
              scale={[2.2, 1.9, 1]}
            >
              <Html
                className="contact"
                position={
                  scrollProgtoMonitorComplete ? [0, 0, 0] : [0, 0, 0.01]
                }
                rotation={[0, 0, Math.PI / 1]}
                scale={
                  scrollProgtoMonitorComplete
                    ? [0.01, 0.01, 10]
                    : [0.19, 0.15, 1]
                }
                sprite={scrollProgtoMonitorComplete}
                transform
              >
                <div
                  className="contact"
                  style={{
                    transform: scrollProgtoMonitorComplete
                      ? "rotate3d(0, 0, 1, -0deg)"
                      : "rotate3d(0, 1, 1, 0deg)",
                    width: "80px",
                    height: "80px",

                    position: "relative",
                  }}
                >
                  <div
                    style={{
                      width: "100%",
                      height: "100%",
                      position: "absolute",
                    }}
                  >
                    <div
                      className="contact-html"
                      style={{
                        transform: scrollProgtoMonitorComplete
                          ? "scale(5.2,6)"
                          : "scale(5.2,6)",
                      }}
                    >
                      <Component />
                    </div>
                  </div>
                </div>
              </Html>
            </mesh>
          </group>


//drawers


          <group
            position={[-1.313, -0.417, 0.12]}
            rotation={[0, 0, -0.018]}
            scale={0.342}
          >
            <mesh
              castShadow
              geometry={nodes.Cube003_2.geometry}
              material={materials["Material.039"]}
              position={[1.91, -0.597, -0.137]}
            >
              <mesh
                castShadow
                geometry={nodes.Cube003_0.geometry}
                material={materials["Material.031"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube003_1.geometry}
                material={materials["Material.030"]}
              />
            </mesh>
          </group>

          
          <group
            position={[-4.135, -0.484, 1.088]}
            rotation={[0, 0, 0.059]}
            scale={0.163}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube005_0.geometry}
              material={materials["Material.025"]}
              position={[5.907, -0.587, -3.149]}
              scale={0.725}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube010_0.geometry}
                material={materials["Material.025"]}
                position={[-0.09, 0.005, 0.695]}
              />
            </mesh>
          </group>

          <group
            position={[3.452, -3.853, 1.647]}
            rotation={[0, 0, -1.551]}
            scale={0.805}
          >




//exit

            {/* <group
              position={[-0.5, -4.235, 0.5]}
              rotation={[0, 0, 0]}
              scale={0.805}
            >
              <mesh
                geometry={nodes2.Cube006_0.geometry}
                material={materials2["Material.031"]}
              />
              <mesh
                geometry={nodes2.Cube006_1.geometry}
                material={materials2["Material.030"]}
              />
              <mesh
                geometry={nodes2.Cube006_2.geometry}
                material={materials2["Material.001"]}
              />
              <mesh
                geometry={nodes2.Cube006_3.geometry}
                material={materials2["Material.002"]}
              />
            </group> */}
          </group>
          <group
            position={[-3.853, -0.896, 1.087]}
            rotation={[0, 0, 2.166]}
            scale={[0.131, 0.183, 0.067]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube009_0.geometry}
              material={materials["Material.035"]}
              position={[-3.248, -3.276, -7.607]}
              scale={0.725}
            />
          </group>
          <group
            position={[-4.138, -0.481, 1.287]}
            rotation={[0, 0, -3]}
            scale={[0.131, 0.183, 0.067]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube012_0.geometry}
              material={materials["Material.035"]}
              position={[-7.22, 0.923, -8.415]}
              scale={-0.637}
            />
          </group>




















//coffee maker





          {/* <group
            position={[-1.443, -0.487, 1.57]}
            rotation={[0, 0, -0.826]}
            scale={0.765}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube015_0.geometry}
              material={materials["Material.034"]}
              position={[0.774, 0.649, -0.184]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015_1.geometry}
                material={materials["Material.032"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015_3.geometry}
                material={materials["Material.021"]}
                position={[0, -0.032, 0]}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube015_2.geometry}
              material={materials["Material.031"]}
              position={[0.774, 0.617, -0.184]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube015_4.geometry}
              material={materials["Material.022"]}
              position={[0.774, 0.649, -0.184]}
            />
          </group> */}





///desk
          <group position={[-2.88, -0.702, 0.565]} scale={0.306}>
            <mesh
              castShadow
              geometry={nodes.Cube016_0.geometry}
              material={materials["Material.023"]}
              position={[1.561, -0.384, -0.468]}
            >
              <mesh
                castShadow
                geometry={nodes.Cube016_1.geometry}
                material={materials["Material.034"]}
              />
              <mesh
                castShadow
                geometry={nodes.Cube016_2.geometry}
                material={materials["Material.039"]}
              />
              <mesh
                castShadow
                geometry={nodes.Cube016_3.geometry}
                material={materials["Material.030"]}
              />
            </mesh>
          </group>
          <group
            position={[-3.835, -0.532, 1.32]}
            rotation={[0, 0, -1.604]}
            scale={0.055}
          >
            <mesh></mesh>
          </group>
          <group position={[-7.169, -0.043, -0.621]} scale={0.422}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube020_1.geometry}
              material={materials["Material.024"]}
              position={[12.239, -6.918, 1.63]}
              scale={[0.249, 0.666, 0.322]}
            />
          </group>
          {!deskchairtransparent && (
            <group
              position={[-2.139, -1.498, 0.048]}
              rotation={[0, 0, -1.175]}
              scale={0.31}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube021_0.geometry}
                material={materials["Material.034"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube021_1.geometry}
                material={materials["Material.032"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube021_2.geometry}
                material={materials["Material.031"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube021_3.geometry}
                material={materials["Material.030"]}
              />
              <mesh
                castShadow
                geometry={nodes.Cube021_4.geometry}
                material={materials["Material.017"]}
                material-roughness={0}
                material-metalness={0.3}
              >
                
              </mesh>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube021_5.geometry}
                material={materials["Material.018"]}
              />
            </group>
          )}
          {/* <group
            position={[-0.346, -3.7, 0.1]}
            rotation={[0, 0, -1.559]}
            scale={0.232}
          >
            <mesh
              geometry={nodes.Cube023_3.geometry}
              material={materials["Material.030"]}
              position={[-0.01, -0.826, 0]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube023_6.geometry}
                material={materials["Material.016"]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube023_0.geometry}
                  material={materials["Material.034"]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube023_1.geometry}
                    material={materials["Material.032"]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube023_2.geometry}
                    material={materials["Material.031"]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube023_4.geometry}
                    material={materials["Material.014"]}
                  />
                  <mesh
                    geometry={nodes.Cube023_5.geometry}
                    material={materials["Material.015"]}
                    position={[0, 0, 0.012]}
                  />
                </mesh>
              </mesh>
            </mesh>
          </group> */}



//plant

          <group
            position={[-3.7, -0.762, 0.068]}
            rotation={[0, 0, -1.4]}
            scale={0.225}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder003_0.geometry}
              material={materials["Material.019"]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003_1.geometry}
                material={materials["Material.020"]}
                scale={[1, 1, 1.228]}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder003_2.geometry}
              material={materials["Material.004"]}
            />
          </group>
        </group>
        <mesh
          receiveShadow
          geometry={nodes.Cylinder012.geometry}
          material={materials["Material.040"]}
          position={[-2.149, -0.188, 2.947]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-1, -0.006, -1]}
        >
          
          <meshStandardMaterial
            color={"#adaba8"}
            metalness={0.5}
            roughness={1}
          />
        </mesh>





///table small






<Lamp/>

///table legs       
        <group position={[-.8, .2, 3.9]} scale={0.35} >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube020_1.geometry}
              material={materials["Material.024"]}
              position={[0,-.1,0]}
              rotation={[-Math.PI/2,0,0]}
              scale={[0.25, 0.6, 0.322]}
            />
            <mesh
          castShadow
          
          material={materials["Material.023"]}
          position={[0,0,0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-2, -0.1, -2]}
        >
          <boxGeometry args={[1,1]}/>
        </mesh>

          </group>


        <mesh
          castShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials["Material.023"]}
          position={[-1.976, 0.117, 2.956]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.674, -0.019, -0.674]}
        >

<Glasses/>


        </mesh>

        <group
          position={[-1.8, 0.2, 2.6]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.08}
        >
          <mesh
            geometry={nodes2.Cylinder007_0.geometry}
            material={materials2["Material.027"]}
          >
            <VaporEffect />
          </mesh>
          <mesh
            geometry={nodes2.Cylinder007_1.geometry}
            material={materials2["Material.026"]}
          />
        </group>

        <group>
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004.geometry}
            material={nodes.Plane004.material}
            position={[0.08, 1.453, 3.99]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={[1.66, 0.094, 0.1]}
          >
            <meshStandardMaterial
              color={"#114035"}
              roughness={0}
              metalness={0.6}
            />
          </mesh> */}

          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006.geometry}
            material={nodes.Plane006.material}
            position={[0.08, 3.11, 2.07]}
            scale={[0.1, 1, 1.92]}
          >
            <meshStandardMaterial
              color={"#114035"}
              roughness={0}
              metalness={0.6}
            />
          </mesh> */}

          {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={nodes.Plane001.material}
          position={[-1.83, 3.112, 0.097]}
          rotation={[0, -1.571, 0]}
          scale={[0.06, 1, 2.01]}
         
          
        ><meshStandardMaterial color={"#0f383b"} roughness={0} metalness={0} /></mesh>
       <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={nodes.Plane007.material}
          position={[-3.842, 1.453, 0.095]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[1.66, 0.094, 0.141]}
          
        ><meshStandardMaterial color={"#0f383b"} roughness={0} metalness={0} /></mesh> */}
        </group>

        <group
          position={[-1.835, 1.435, 0.06]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.095, 1.676, 2.003]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={materials["Material.007"]}
            
          >
            <meshStandardMaterial color={"#061713"} metalness={0} />
          </mesh>
        </group>
        <group
          position={[0.049, 1.433, 2.116]}
          scale={[0.144, 1.676, 1.873]}
        ></group>

        <group position={[0.08, 1.433, 2.07]} scale={[0.1, 1.676, 1.91]}>
          <mesh
          castShadow
          receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials["Material.007"]}
            material-roughness={1}
            material-metalness={0}
          >
            <meshStandardMaterial color={"#061713"} />
          </mesh>

          <group
            position={[-2.354, 0.3, -0]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.37}
          >
            <Corkboard />
          </group>
        </group>

        <group position={[0, -0.1, 0]} scale={[1, 0.69, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={materials["Material.004"]}
            position={[-1.854, -0.297, 1.994]}
            scale={[1.969, 0.095, 1.997]}
          >
            <meshStandardMaterial
              color={"#adaba8"}
              roughness={0}
              metalness={0.98}
            />
          </mesh>

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={nodes.Plane002.material}
            position={[-1.825, -0.303, 3.992]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[2.02, 0.094, 0.101]}
          >
            
            <meshStandardMaterial
              color={"#adaba8"}
              roughness={0}
              metalness={0.98}
            />
          </mesh>

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003.geometry}
            position={[-3.844, -0.303, 1.972]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[2.02, 0.094, 0.101]}
          >
            <meshStandardMaterial
              color={"#adaba8"}
              roughness={0}
              metalness={0.98}
            />
          </mesh>
        </group>
      </group>
      </group>
    </>
  );
}

useGLTF.preload("compressedOffice.glb");
